#define CONCAT_H(A,B) A ## X
#define CONCAT(A,B) CONCAT_H(A,B)

#if IS_ENVIRONMENT_HW
#define IS_FRAMEWORK_ARDUINO 1
#define IS_FRAMEWORK_NATIVE 0
#endif


#if IS_ENVIRONMENT_NATIVE
#define IS_FRAMEWORK_ARDUINO 0
#define IS_FRAMEWORK_NATIVE 1
#endif